# Generated by Django 2.2.10 on 2020-12-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelName', models.CharField(max_length=50)),
                ('hotelAddress', models.CharField(max_length=50)),
                ('singleRooms', models.CharField(max_length=50)),
                ('doubleRooms', models.CharField(max_length=50)),
                ('tripleRooms', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': ' hotel',
                'verbose_name_plural': ' hotels',
            },
        ),
    ]
