# Generated by Django 2.2.10 on 2020-12-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('fees', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
    ]
