# Generated by Django 2.2.10 on 2021-01-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.CharField(default='ghjk', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(default=',jkl', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='fees',
            field=models.CharField(max_length=50),
        ),
    ]
