# Generated by Django 2.2.10 on 2021-01-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210105_2218'),
        ('service', '0002_auto_20210105_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='User',
            field=models.ManyToManyField(to='members.Users'),
        ),
    ]
