# Generated by Django 2.2.10 on 2021-01-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='User',
        ),
    ]
