# Generated by Django 2.2.10 on 2021-01-14 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20210112_0527'),
        ('sightseeing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('email', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Users')),
            ],
            options={
                'verbose_name': 'query',
                'verbose_name_plural': 'querys',
            },
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
