# Generated by Django 2.2.10 on 2020-12-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('fees', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
        ),
    ]
