# Generated by Django 2.2.10 on 2021-01-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_remove_conductedfees_totalfeese'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductedfees',
            name='totalFees',
            field=models.CharField(default='gggedgfd', max_length=50),
            preserve_default=False,
        ),
    ]
