# Generated by Django 2.2.10 on 2021-01-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_users_service'),
        ('room', '0001_initial'),
        ('fees', '0003_conductedfees_totalfees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductedfees',
            name='room',
        ),
        migrations.AddField(
            model_name='conductedfees',
            name='room',
            field=models.ManyToManyField(to='room.room'),
        ),
        migrations.RemoveField(
            model_name='conductedfees',
            name='user',
        ),
        migrations.AddField(
            model_name='conductedfees',
            name='user',
            field=models.ManyToManyField(to='members.Users'),
        ),
    ]
