# Generated by Django 2.2.10 on 2021-01-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_users_service'),
        ('room', '0001_initial'),
        ('fees', '0004_auto_20210108_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductedfees',
            name='room',
        ),
        migrations.AddField(
            model_name='conductedfees',
            name='room',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='room.room'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='conductedfees',
            name='user',
        ),
        migrations.AddField(
            model_name='conductedfees',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='members.Users'),
            preserve_default=False,
        ),
    ]
