# Generated by Django 2.2.10 on 2021-01-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_auto_20210108_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductedfees',
            name='room',
            field=models.CharField(max_length=50),
        ),
    ]
