# Generated by Django 2.2.10 on 2021-01-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_auto_20210112_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductedfees',
            name='adminFees',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
