# Generated by Django 2.2.10 on 2021-01-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_conductedfees_adminfees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductedfees',
            name='totalFees',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
