# Generated by Django 2.2.10 on 2021-01-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210105_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='cardNumber',
        ),
        migrations.RemoveField(
            model_name='users',
            name='cardType',
        ),
        migrations.RemoveField(
            model_name='users',
            name='checkIn',
        ),
        migrations.RemoveField(
            model_name='users',
            name='expiryDate',
        ),
    ]
