# Generated by Django 2.2.10 on 2021-01-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_service_user'),
        ('members', '0003_auto_20210105_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='service',
            field=models.ManyToManyField(to='service.service'),
        ),
    ]
