# Generated by Django 2.2.10 on 2021-01-09 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_user'),
        ('members', '0004_users_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Payment'),
        ),
    ]
