# Generated by Django 2.2.10 on 2021-01-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_users_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Payment'),
        ),
    ]
