# Generated by Django 2.2.10 on 2021-01-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20210109_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dateOfBirth',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobileNumber',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
