# Generated by Django 2.2.10 on 2021-01-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20210112_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='service',
            field=models.ManyToManyField(null=True, to='service.service'),
        ),
    ]
