# Generated by Django 2.2.10 on 2021-01-05 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_app', '0001_initial'),
        ('members', '0003_auto_20210105_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roomCapacity', models.CharField(max_length=50)),
                ('roomType', models.CharField(max_length=50)),
                ('startDate', models.CharField(max_length=50)),
                ('endDate', models.CharField(max_length=50)),
                ('checkIn', models.BooleanField(default=True)),
                ('hotelName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Users')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'bookings',
            },
        ),
    ]
