# Generated by Django 2.2.10 on 2021-01-12 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210109_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bokikngType',
            new_name='bookingType',
        ),
    ]
