# Generated by Django 2.2.10 on 2021-01-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210112_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotelName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
