# Generated by Django 2.2.10 on 2021-01-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_roomnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
