# Generated by Django 2.2.10 on 2021-01-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210112_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkIn',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
