# Generated by Django 2.2.10 on 2021-01-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='userName',
            field=models.CharField(default='hjkl', max_length=50),
            preserve_default=False,
        ),
    ]
