# Generated by Django 2.2.10 on 2020-12-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardType', models.CharField(max_length=50)),
                ('cardNumber', models.CharField(max_length=50)),
                ('expiryDate', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'creditCard',
                'verbose_name_plural': 'creditCards',
            },
        ),
    ]
